### PR TITLE
Upgrade no async deps

### PR DESCRIPTION
**Pull request by eguzki**
Changes applied:
* bugsnag 6.6.4 ->  6.22.1
* sinatra, sinatra-contrib 2.0.3 -> 2.0.8.1 
  * backports 3.11.3 -> 3.21.0
  *  mustermann (1.0.2) -> mustermann (1.1.1)
  * rack-protection (2.0.3) -> rack-protection (2.0.8.1)
  * tilt (2.0.8) -> tilt (2.0.10)
*  rake 13.0.1 -> 13.0.6

Analysis on other no async deps (as of today Nov 15th 2021). Test and Development gems not taken into account.

| library | current version constraint | currently used version | latest available | action |
| --- | --- | --- | --- | --- |
| aws-sdk | `= 2.4.2` | `2.4.2` | `3.1.0` | Fixed to version |
| whenever | `= 0.9.7` | `0.9.7` | `1.0.0` | Fixed to version |
| scientist | `= 1.0.0` | `1.0.0` | `1.6.2` | Fixed to version |
| statsd-ruby | `= 1.4.0` | `1.4.0` | `1.5.0` | Fixed to version |
| airbrake | `= 4.3.1` | `4.3.1` | `12.0.0` | Fixed to version |
| daemons | `= 1.2.4` | `1.2.0` | `1.4.0` | Fixed to version |
| builder | `= 3.2.3` | `3.2.3` | `3.2.4 | Fixed to version |
| pg | `~> 1.2.3` | `1.2.3` | `1.2.3` | latest. No need to update |
| hiredis | `~> 0.6.1` | `0.6.3` | `0.6.3` | latest. No need to update |
| yajl-ruby | `~> 1.3.1` | `1.3.1` | `1.4.1` | no update feasible with the current version specifier |
| redis-namespace | `~> 2.16.1` | `2.16.1` | `2.20.1` | no update feasible with the current version specifier |
| gli | `~> 1.8.0` | `1.8.0` | `1.8.0` | latest. No need to update |
| rack | `~> 2.1.4` | `2.1.4` | `2.2.3` | no update feasible with the current version specifier |
| yabeda-prometheus | `~> 0.5.0` | `0.5.0` | `0.5.0` | latest. No need to update |
| puma | Fork based on `4.3.7` | Fork based on `4.3.7` | latest minor `4.3.10` latest major `5.5.2` | Pending to decide |
| resque | Fork based on `1.27.4` | Fork based on `1.27.4` | latest minor `1.27.4` latest major `2.2.0` | latest minor version |
| redis | Fork based on `4.1.3` | Fork based on `4.1.3` | latest `4.5.1` | Pending to decide |

### CODE REVIEW

**Comment by unleashed** [comment]
@eguzki is this blocked or otherwise waiting to be closer in time to a release?

**Comment by eguzki** [comment]
This is not blocked

**Comment by unleashed** [comment]
So looking for reviews? Or should we consider re-updating after so much time has elapsed?

**Comment by eguzki** [comment]
I would say, looking for review. Re-updating can always be done (needs to be done)

**Review by unleashed — COMMENTED** [review]
Ok, these are very conservative updates. We should look into updating the minors of a few gems - for Puma updating to the latest 4.3.X should be safe. Resque would need a lot more care though.

**Comment by eguzki** [comment]
we are not applying this change for now. Maybe in the future.

**Pull request closed without merging**
