### PR TITLE
clean-up: delete unnecessary 'before' in Utilization specs

### PR DESCRIPTION
**Pull request by davidor**
Minor clean-up extracted from #96.

The other before blocks already set up everything needed without regards of previous contents.

### CODE REVIEW

**Comment by unleashed** [comment]
Looks good, but would benefit from explaining _why_ it is not needed (ie. other before blocks already set up everything needed without regards of previous contents).

**Comment by davidor** [comment]
Yes, it's in the commit description.

**Comment by unleashed** [comment]
IFTFY in the PR description.

**Comment by davidor** [comment]
bors retry

**Pull request merged**
