### PR TITLE
Update CI image to include Ruby 2.6

### PR DESCRIPTION
**Pull request by davidor**
Also, configure CircleCI to pass the tests on Ruby 2.6 too.

### CODE REVIEW

**Comment by davidor** [comment]
There's one test that fails on Ruby 2.6:
```
Error: test: Delete all tokens for a given service, app and user(AccessTokenTest): ArgumentError: wrong number of arguments (given 1, expected 4)
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:115:in `block in remove_tokens'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `<<'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `<<'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `<<'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each_slice'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each_slice'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `each'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `inject'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:147:in `remove_token_set_by'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:135:in `remove_tokens_by'
/home/ruby/app/lib/3scale/backend/oauth/token_storage.rb:118:in `remove_tokens'
/home/ruby/app/test/integration/oauth/access_token_test.rb:723:in `block in <class:AccessTokenTest>'
```

Also, there are some deprecation messages like this one: `warning: constant ::Fixnum is deprecated`

**Comment by miguelsorianod** [comment]
It seems that it was deprecated indeed. Fixnum and Bignum seem to have been unified into Integer, although they still exists as (deprecated) alias to that:

https://bugs.ruby-lang.org/issues/12005

**Comment by unleashed** [comment]
> Also, there are some deprecation messages like this one: `warning: constant ::Fixnum is deprecated`

IIRC that happened in 2016, with the release of Ruby 2.4...

**Comment by davidor** [comment]
Added a new commit that fixes the problem mentioned in my comment above, and another one that solves the deprecation warnings.

The PR is ready to be reviewed.

**Pull request merged**
