### PR TITLE
Allow deleting the default service when it's the only one for the provider

### LINKED ISSUE #50: Provide a way to delete default services
Right now there's no way to delete the default service of a provider. It probably makes sense to allow deleting it when it's the only one left.

### PR DESCRIPTION
**Pull request by davidor**
Closes #50

### CODE REVIEW

**Comment by davidor** [comment]
@miguelsorianod In the acceptance tests, we verify the JSON returned. From there, we cannot check the exception that was raised and captured, we can just verify the error message returned in the JSON.

**Comment by miguelsorianod** [comment]
I see. This kind of tests use the API endpoints directly instead of using pisoni so there is no access to the exceptions :+1:

**Comment by davidor** [comment]
bors r=@miguelsorianod

**Pull request merged**
