### PR TITLE
Fix issues for CI environments

### PR DESCRIPTION
**Pull request by eguzki**
- [x] Fix sleep time for postgress to start
- [x] docker: remove allocating TTY required for some CI environments

### CODE REVIEW

**Comment by unleashed** [comment]
Is there any reason the `-ti` removal is needed other than "things break"?

**Comment by eguzki** [comment]
let me answer with a question:

what is the reason to keep stdin open (`-i`) or allocate tty (`-t`) on docker run when you are running tests?

I think it is better to run in non-interactive mode and potential environments from CI would not fail. 

Maybe we can leave `-t` for TTY support for color formatting.

**Comment by unleashed** [comment]
an answer is not a question and you are not Galician, so not entitled to do that... :)

**Comment by unleashed** [comment]
That said... yes, this is meant to have colors in the `make test` output, and I think `-i` could go away. In any case a special invocation just for CI could leave out the `-t` if really needed.

**Comment by eguzki** [comment]
bors r=@unleashed

**Pull request merged**
